Add/hook use debounce2 update
artemiusV/github_search_api_redux pull request #5
Opened 2024-04-10 08:50 UTC by artemiusV

2024-04-12 09:51 UTC, AdammmVV commented on src/useDebounce.jsx
> +export default useDebounceEffect;
rework custom hook [useDebounce](https://dev.to/mukhammadsobirov/kastomnyi-react-khuk-usedebounce-2b3l)

2024-04-12 09:51 UTC, AdammmVV commented on src/components/pages/Home/Home.tsx
> +    },
all asynchronous actions are performed in Thunk

2024-04-12 09:51 UTC, AdammmVV commented on src/components/pages/Home/Home.tsx
>    const [limit, setLimit] = useState<number>(10);
do not use magic number use constants `10`

2024-04-12 09:51 UTC, AdammmVV commented on src/components/pages/Home/Home.tsx
>  type HomeProps = {};
If you do not use Props, delete it

2024-04-30 11:06 UTC, suveiko requested changes

2024-04-30 11:06 UTC, suveiko commented on src/components/pages/Home/Home.tsx
> +  console.log(usersSearch);
убери консоль лог

2024-04-30 11:06 UTC, suveiko commented on src/store/userSlice/userSlice.ts
> +  { response1: any; response2: any },
поправь, никаких any+ корректны нейминг

2024-04-30 11:06 UTC, suveiko commented on src/store/userSlice/userSlice.ts
> +      console.error("Error fetching user information");
убери консоль,юзеру это не о чем не говорит

2024-04-30 11:06 UTC, suveiko commented on src/store/userSlice/userSlice.ts
> +    return thunkApi.rejectWithValue("Error fetching user information");
сделай глобальный хелпер, который будет вызывать toast

2024-04-30 11:06 UTC, suveiko commented on src/useDebounce.jsx
> +//кастомный хук можно его переиспользовать в любов участке кода
коммент лишний

2024-04-30 11:06 UTC, suveiko commented on src/useDebounce.jsx
> +const useDebounceEffect = (callback, delay, deps) => {
typescript?

2024-04-30 11:06 UTC, suveiko commented on src/store/userSlice/searchSlice.ts
> +// export const { setRepos, setUser } = userSlice.actions;
удали

2024-04-30 11:06 UTC, suveiko commented on src/store/userSlice/searchSlice.ts
> +  any[],
поправь any

2024-04-30 11:06 UTC, suveiko commented on src/store/userSlice/searchSlice.ts
> +        console.error("Ошибка при загрузке пользователей", action.error);
тоже самое

2024-04-30 11:06 UTC, suveiko commented on src/store/userSlice/searchSlice.ts
> +  isLoadingSearch: boolean;
isUserSearching

2024-04-30 11:06 UTC, suveiko commented on src/components/pages/Home/Home.tsx
> +  console.log(getValues());
убери

2024-04-30 11:06 UTC, suveiko commented on src/components/pages/Home/Home.tsx
> +  const TestNotification = () => {
не совсем понял, зачем тут 2 обертки?

2024-05-04 09:03 UTC, merged